#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e    # exit immediately if an error occurs
exec 1>&2 # ensure any output is sent to stderr

#
# Allow other modules to read module configuration and status
#
redis-exec SADD "${AGENT_ID}/roles/reader" "get-*" "list-*"

#
# Allow the instance itself to run some subtasks during operations
#
redis-exec SADD "${AGENT_ID}/roles/selfadm" \
    "configure-module" \
    "get-configuration" \
    "create-webhook" \
    "update-webhook" \
    "delete-webhook" \
    "list-webhooks" \
    "test-webhook" \
    "start-mail-monitor" \
    "stop-mail-monitor" \
    "get-mail-monitor-status"
