#!/usr/bin/env python3

#
# Copyright (C) 2023 Lee M. Lwando <leemlwando@gmail.com>
# SPDX-License-Identifier: MIT
#

import json
import sys
import os
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Connect to redis
rdb = agent.redis_connect()

# Set default configuration
rdb.hset(f'module/{agent.environ["MODULE_ID"]}/configuration', mapping={
    'imap_host': '127.0.0.1',
    'imap_port': '993',
    'imap_ssl': 'true',
    'webhook_timeout': '30',
    'max_retries': '3',
    'check_interval': '60'
})

# Set default state
rdb.hset(f'module/{agent.environ["MODULE_ID"]}/state', mapping={
    'scheduler_enabled': 'true',
    'last_check': '',
    'total_processed': '0'
})

agent.set_weight(os.path.join(os.environ['AGENT_INSTALL_DIR'], "actions", "configure-module"))
