#!/usr/bin/env python3

#
# Copyright (C) 2024 KSM Management Consultants
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

def main():
    """Return current module configuration"""
    config = {
        'webhook_server_enabled': os.getenv("WEBHOOK_SERVER_ENABLED", "true").lower() == "true",
        'webhook_server_url': os.getenv("WEBHOOK_SERVER_URL", "http://127.0.0.1:8080"),
        'webhook_server_image': os.getenv("WEBHOOK_SERVER_IMAGE", "ghcr.io/leemlwando/ns8-mail-webhooks-server:latest"),
        'imap_server': os.getenv("IMAP_SERVER", "localhost"),
        'imap_port': int(os.getenv("IMAP_PORT", "993")),
        'imap_username': os.getenv("IMAP_USERNAME", ""),
        'mongodb_url': os.getenv("MONGODB_URL", "mongodb://127.0.0.1:27017/webhooks"),
        'redis_url': os.getenv("REDIS_URL", "redis://127.0.0.1:6379"),
        'debug': os.getenv("DEBUG", "false").lower() == "true"
    }
    
    # Don't include password in the response for security
    if config['imap_username']:
        config['imap_password_set'] = bool(os.getenv("IMAP_PASSWORD"))
    
    json.dump(config, fp=sys.stdout)

if __name__ == "__main__":
    main()
