#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

config = {
    "mongodb_url": os.getenv("MONGODB_URL", ""),
    "mail_server_uuid": os.getenv("MAIL_SERVER_UUID", ""),
    "webhooks_collection": os.getenv("WEBHOOKS_COLLECTION", "webhooks"),
    "events_collection": os.getenv("EVENTS_COLLECTION", "events"),
    "settings_collection": os.getenv("SETTINGS_COLLECTION", "settings"),
    "triggers_collection": os.getenv("TRIGGERS_COLLECTION", "triggers"),
    "logs_collection": os.getenv("LOGS_COLLECTION", "logs")
}

json.dump(config, fp=sys.stdout)
