#!/usr/bin/env python3

"""
Get Configuration Action for NS8 Mail Webhooks

Copyright (C) 2025 Lee M. Lwando <leemlwando@gmail.com>
Licensed under GPL-3.0
"""

import json
import sys
import os

# Add module's python package to path
module_id = os.environ.get('MODULE_ID', 'webhooks1')
sys.path.insert(0, f'/home/{module_id}/.local/share/container/pypkg')

from config_manager import ConfigManager

def main():
    try:
        # Initialize config manager
        config_mgr = ConfigManager(module_id)
        
        # Read current configuration
        config = config_mgr.read_config()
        
        json.dump({
            'status': 'success',
            'configuration': config
        }, sys.stdout)
        
    except Exception as e:
        json.dump({
            'status': 'error',
            'error': str(e)
        }, sys.stdout)
        sys.exit(1)

if __name__ == '__main__':
    main()
