#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

# Return the module instance name
name_info = {
    "name": os.environ.get('MODULE_ID', 'mail-webhooks')
}

json.dump(name_info, fp=sys.stdout)
sys.exit(0)
